"use client";

import Link from "next/link";
import { useMemo, useState, type ReactNode } from "react";

import { getMonogram, groupRecords, hubGroupLabels, hubStatusLabels, type HubRecord } from "./hub-model";

type Props = {
  appointments: readonly HubRecord[];
  clients: readonly HubRecord[];
  preferredSection: "danisanlar" | "talepler";
  [key: string]: unknown;
};

const Icon = ({ children }: { children: string }) => <span className="text-[15px] leading-none" aria-hidden>{children}</span>;

export function DashboardAdmin({ appointments, clients, preferredSection }: Props) {
  const [activeMenuItem, setActiveMenuItem] = useState(preferredSection === "danisanlar" ? "clients" : "requests");
  const [query, setQuery] = useState("");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [showSearch, setShowSearch] = useState(false);
  const [notice, setNotice] = useState("");
  const records = activeMenuItem === "clients" ? clients : appointments;
  const filtered = useMemo(() => records.filter((record) => `${record.name} ${record.lastAction} ${record.contactPhone}`.toLocaleLowerCase("tr-TR").includes(query.toLocaleLowerCase("tr-TR"))), [query, records]);
  const selected = filtered.find((record) => record.id === selectedId) ?? filtered[0] ?? null;
  const nav = [
    ["Çalışma alanım", [["home", "Genel bakış", "⌂"]]],
    ["Randevular", [["requests", "Talep kuyruğu", "▦"], ["calendar", "Randevu operasyonu", "◷"], ["summary", "Müsaitlik özeti", "▤"]]],
    ["Danışanlar", [["clients", "Danışan kayıt merkezi", "◉"], ["client-management", "Danışan yönetimi", "○"], ["new", "Yeni danışan", "+"]]],
    ["Finans", [["finance", "Ödeme ve planlar", "₺"]]],
    ["Site yönetimi", [["settings", "İletişim ayarları", "⌁"], ["services", "Hizmet ve terapist", "✺"]]],
  ] as const;
  const selectMenu = (id: string) => {
    if (id === "clients" || id === "requests") { setActiveMenuItem(id); setSelectedId(null); return; }
    if (id === "new") { window.location.assign("/yonetim/danisan-olustur"); return; }
    if (id === "finance") { window.location.assign("/yonetim/odemeler"); return; }
    if (id === "settings" || id === "services") { window.location.assign(`/yonetim/hub?alan=${id}`); return; }
    setNotice("Bu alan mevcut yönetim akışına yönlendirilmek üzere hazırlanıyor.");
  };
  return <div className="flex h-screen min-h-[760px] overflow-hidden bg-[#eae8e1] font-sans text-[#111827]">
    <aside className="h-screen w-60 shrink-0 bg-[#eae8e1] flex flex-col select-none">
      <div className="flex h-16 items-center gap-3 border-b border-[#e2e1df]/60 px-4">
        <div className="w-7 h-7 rounded-full flex items-center justify-center shrink-0 border border-black/10 bg-white text-[10px] font-bold">BA</div>
        <div className="flex items-center gap-2 whitespace-nowrap"><span className="font-bold text-[#323130] text-sm tracking-tight">Berfin Akbaş</span><span className="w-px h-3.5 bg-[#dcdad3]"/><span className="text-xs text-[#605e5c] font-semibold">Yönetim</span></div>
      </div>
      <div className="flex-1 overflow-y-auto py-5 space-y-5 px-4">
        <div className="flex items-center justify-between px-2"><span className="text-xl font-bold text-gray-800 tracking-tight">Menü</span><button className="w-7 h-7 rounded-full border border-gray-400/20 text-gray-500" onClick={() => setNotice("Menü açık.")}>←</button></div>
        {nav.map(([title, items]) => <div key={title} className="space-y-1.5 pt-1"><span className="px-3 text-[12px] font-bold text-gray-900 block mb-1">{title}</span><div className="space-y-1">{items.map(([id,label,icon]) => <button key={id} onClick={() => selectMenu(id)} className={`w-full flex items-center gap-3.5 px-3 py-1.5 rounded-full text-sm transition-colors cursor-pointer ${activeMenuItem === id ? "bg-[#d2fc5c] text-black font-bold" : "text-gray-500 hover:bg-white/30 hover:text-black font-semibold"}`}><div className={`w-7 h-7 rounded-full flex items-center justify-center shrink-0 border ${activeMenuItem === id ? "border-black/15" : "border-gray-400/20"}`}><Icon>{icon}</Icon></div><span className="truncate">{label}</span></button>)}</div></div>)}
      </div>
    </aside>
    <main className="flex min-w-0 flex-1 flex-col">
      <header className="h-16 px-6 flex items-center justify-between shrink-0 relative"><div className="flex-1"/><div className="flex items-center gap-1">{[["⌕","Ara"],["◷","Randevular"],["+","Yeni danışan"],["♧","İçgörüler"],["▽","Filtre"],["⚙","Ayarlar"],["?","Yardım"],["◉","Destek"]].map(([icon,title], index) => <button key={title} title={title} onClick={() => index === 2 ? window.location.assign("/yonetim/danisan-olustur") : index === 1 ? window.location.assign("/yonetim/randevular") : index === 0 || index === 4 ? setShowSearch(true) : setNotice(`${title} etkin.`)} className="w-9 h-9 rounded-full border border-gray-400/20 flex items-center justify-center hover:bg-white/30 text-gray-500 hover:text-black transition-colors"><Icon>{icon}</Icon></button>)}<div className="relative ml-1 w-9 h-9 rounded-full bg-white border border-gray-400/20 flex items-center justify-center text-xs">BA<span className="absolute bottom-0 right-0 w-2.5 h-2.5 bg-emerald-500 rounded-full border-2 border-white"/></div></div></header>
      <div className="flex min-h-0 flex-1 gap-2 px-0 pb-4">
        <section id="my-work-panel" className="w-[340px] bg-[#fcfbfa] rounded-[2.5rem] border border-gray-300/40 shadow-sm flex flex-col overflow-hidden h-[calc(100vh-5rem)] shrink-0 select-none">
          <div className="p-6 pb-3 flex items-center justify-between"><h2 className="text-2xl font-bold text-gray-900 tracking-tight">My Work</h2><div className="flex items-center gap-1.5"><button onClick={() => {setQuery("");setSelectedId(null)}} title="Yenile" className="w-8 h-8 rounded-full border border-gray-400/20 bg-white/40">↻</button><button onClick={() => setNotice(`${filtered.length} kayıt listeleniyor.`)} title="Kuyruk" className="w-8 h-8 rounded-full border border-gray-400/20 bg-white/40">▤</button><button onClick={() => setShowSearch(!showSearch)} title="Ara" className={`w-8 h-8 rounded-full border ${showSearch ? "bg-black border-black text-white" : "border-gray-400/20 bg-white/40 text-gray-500"}`}>⌕</button></div></div>
          {showSearch && <div className="px-6 pb-3"><div className="relative"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Danışan veya işlem ara..." autoFocus className="w-full bg-white/60 border border-gray-300/60 rounded-xl py-1.5 px-3 text-xs focus:outline-none focus:border-black/50"/></div></div>}
          <div className="px-6 pb-3"><div className="flex items-center justify-center gap-2"><div className="flex-1 h-px bg-gray-200/60"/><span className="text-[10px] font-bold tracking-widest text-gray-400 uppercase">{activeMenuItem === "clients" ? "Danışanlar" : "Bugün"}</span><div className="flex-1 h-px bg-gray-200/60"/></div></div>
          <div className="flex-1 overflow-y-auto px-4 pb-6 space-y-4">{filtered.length === 0 ? <div className="text-center py-10 px-4 text-xs text-gray-400 font-semibold">Bu bölümde kayıt bulunmuyor.</div> : groupRecords(filtered).map((bucket) => <div key={bucket.group} className="space-y-4"><div className="flex items-center justify-center gap-2"><div className="flex-1 h-px bg-gray-200/60"/><span className="text-[9px] font-bold tracking-widest text-gray-400 uppercase">{hubGroupLabels[bucket.group]}</span><div className="flex-1 h-px bg-gray-200/60"/></div>{bucket.items.map((record) => <button key={record.id} onClick={() => setSelectedId(record.id)} className={`w-full text-left transition-all duration-200 rounded-[2rem] p-4 flex flex-col gap-3 shadow-xs border ${selected?.id === record.id ? "bg-[#eafda8] border-black/[0.04]" : "bg-white hover:bg-gray-50/50 border-gray-200/60"}`}><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2.5"><div className="w-10 h-10 rounded-full bg-[#dcead1] border border-black/5 flex items-center justify-center text-xs font-bold">{getMonogram(record.name)}</div><div><span className="text-xs font-bold leading-tight block text-gray-800">{record.name}</span><span className="text-[10px] text-gray-400 font-semibold">{record.lastAction}</span></div></div><div className="w-7 h-7 rounded-full bg-gray-50 text-gray-400 border border-gray-200 flex items-center justify-center">{record.contactEmail ? "✉" : "☎"}</div></div><div className="flex items-center justify-between"><div className="px-2 py-0.5 rounded-full text-[8px] font-bold tracking-wider bg-gray-50 text-gray-400 border border-gray-100">{record.kind === "danisan" ? "DANIŞAN" : "TALEP"}</div><div className="w-6 h-6 rounded-full flex items-center justify-center text-[10px] font-extrabold shadow-xs border bg-[#ecfdf5] text-emerald-600 border-emerald-100">{record.score}</div></div></button>)}</div>)}</div>
        </section>
        <Workspace record={selected} notice={notice} clearNotice={() => setNotice("")} />
      </div>
    </main>
  </div>;
}

function Workspace({ record, notice, clearNotice }: { record: HubRecord | null; notice: string; clearNotice: () => void }) {
  const [tab,setTab] = useState("Özet");
  if (!record) return <section className="flex-1 bg-gradient-to-br from-[#eafda8]/75 via-white/80 to-white/95 rounded-[2.5rem] border border-gray-300/40 p-5 h-[calc(100vh-5rem)] flex items-center justify-center text-sm font-semibold text-gray-400">Listeden bir danışan seçin.</section>;
  const stage = ["Talep", "Kontrol", "Onay", "Görüşme"];
  const stageIndex = ["talep","kontrol","onay","gorusme"].indexOf(record.stage);
  return <section id="workspace-panel" className="flex-1 min-w-0 bg-gradient-to-br from-[#eafda8]/75 via-white/80 to-white/95 rounded-[2.5rem] border border-gray-300/40 p-5 flex flex-col h-[calc(100vh-5rem)] shadow-sm overflow-y-auto select-none gap-5">
    {notice && <button onClick={clearNotice} className="rounded-xl bg-[#fff7d6] p-2 text-left text-xs font-semibold">{notice} ×</button>}
    <div className="flex flex-wrap items-center justify-between gap-2 border-b border-black/[0.04] pb-4"><div className="flex items-center gap-1">{[["▣","Kaydet",()=>record.profileHref && window.location.assign(record.profileHref)],["+","Yeni",()=>window.location.assign("/yonetim/danisan-olustur")],["⌫","Kapat",()=>history.back()],["↻","Yenile",()=>window.location.reload()],["⌘","Erişimi denetle",()=>alert("Bu kayıt için mevcut görüntüleme yetkisi doğrulandı.")],["▤","PDF",()=>window.print()],["♙","Kalite",()=>document.getElementById("record-quality")?.scrollIntoView({behavior:"smooth"})],["⌁","Süreç",()=>document.getElementById("record-process")?.scrollIntoView({behavior:"smooth"})]].map(([icon,label,action]) => <button key={String(label)} onClick={action as () => void} className="flex items-center gap-1.5 px-3 py-1.5 rounded-full hover:bg-black/[0.03] text-gray-700 hover:text-black text-xs font-semibold"><Icon>{String(icon)}</Icon><span>{label}</span></button>)}</div><button className="w-8 h-8 rounded-full hover:bg-black/[0.03]">•••</button></div>
    <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white/40 p-4 rounded-3xl border border-white/60 shadow-xs"><div className="flex items-center gap-3.5"><div className="w-14 h-14 rounded-full bg-[#dcead1] border-2 border-white shadow-sm flex items-center justify-center font-bold">{getMonogram(record.name)}</div><div className="flex flex-col gap-1"><h1 className="text-xl font-bold text-gray-900 tracking-tight">{record.name}</h1><div className="flex items-center gap-1.5"><span className="px-2.5 py-0.5 bg-[#eafda8] text-black text-[9px] font-bold uppercase tracking-wider rounded-full">{record.kind === "danisan" ? "Danışan" : "Talep"}</span><span className="px-2.5 py-0.5 bg-black text-white text-[9px] font-bold uppercase tracking-wider rounded-full">KAYIT GÖRÜNÜMÜ</span></div></div></div><div className="flex items-center gap-6 text-[11px] font-medium text-gray-500 pr-2"><Stat label="KAYNAK" value={record.channel}/><Stat label="HİZMET" value={record.service}/><Stat label="DURUM" value={hubStatusLabels[record.status]}/><Stat label="REFERANS" value={record.reference}/></div></div>
    <div id="record-process" className="bg-white/40 border border-white/60 rounded-3xl p-3.5 flex flex-col md:flex-row md:items-center justify-between gap-3 shadow-xs"><div className="flex flex-col gap-0.5 pl-2.5"><span className="text-xs font-bold text-gray-900 leading-tight">Danışan işlem süreci</span><span className="text-[10px] text-gray-400 font-semibold">{record.lastActionAt}</span></div><div className="flex flex-1 items-center justify-end gap-1 text-[11px] font-bold">{stage.map((label,index) => <div key={label} className="flex items-center gap-1"><div className={`flex items-center ${index===0?"rounded-l-full":"rounded-lg"} ${index===stage.length-1?"rounded-r-full":""} ${index <= stageIndex ? "bg-teal-500 text-white" : "bg-white/70 border border-gray-200 text-gray-600"} px-4 py-1.5`}><span>{index < stageIndex ? "✓" : index === stageIndex ? "●" : "◌"}</span><span>{label}</span></div>{index<stage.length-1 && <span className="text-gray-300">›</span>}</div>)}</div></div>
    <div className="flex items-center gap-1 border-b border-black/[0.03] pb-2 text-xs font-bold">{["Özet","İlişki analizi","Detaylar","İlgili"].map(item => <button onClick={() => setTab(item)} key={item} className={`px-5 py-2 rounded-full ${tab===item ? "bg-black text-white shadow-xs" : "text-gray-400 hover:text-black"}`}>{item}</button>)}</div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-5"><div className="flex flex-col gap-5"><Card title="İletişim"><Row label="Telefon" value={record.contactPhone}/><Row label="E-posta" value={record.contactEmail}/><Row label="Hizmet" value={record.service}/><Row label="Planlanan" value={record.plannedAt}/></Card><Card title="Bağlantılar">{record.connections.length ? record.connections.map(c=><Row key={c.name} label={c.relation} value={c.name}/>) : <Row label="Durum" value="Bağlantılı kayıt yok"/>}</Card></div><div className="flex flex-col gap-5"><Card title="Sıradaki adımlar">{record.nextSteps.length ? record.nextSteps.map((step,index)=><div key={step.title} className="rounded-2xl border border-gray-200/80 p-3 mb-2"><div className="flex gap-3"><span className="w-6 h-6 rounded-lg bg-[#201d1d] text-white text-xs flex items-center justify-center font-bold">{index+1}</span><div><p className="text-xs font-bold">{step.title}</p><p className="text-[10px] text-gray-400 mt-1">{step.detail}</p><p className="text-[10px] text-teal-600 font-bold mt-2">{step.due}</p></div></div></div>) : <p className="text-xs text-gray-400">Planlanmış adım yok.</p>}</Card><Card title="Zaman çizelgesi">{record.timeline.length ? record.timeline.map(item=><div key={`${item.at}-${item.label}`} className="flex gap-5 text-[10px] py-2"><span className="text-teal-600 font-bold">{item.at}</span><span className="text-gray-500">{item.label}</span></div>) : <p className="text-xs text-gray-400">Zaman çizelgesi henüz boş.</p>}</Card></div><div className="flex flex-col gap-5"><Card title="Kayıt skoru"><div id="record-quality" className="flex items-center justify-center gap-5 py-3"><div className="w-24 h-24 rounded-full border-[8px] border-emerald-500 flex flex-col justify-center items-center"><b className="text-3xl">{record.score}</b><span className="text-[8px] font-bold text-emerald-600">GRADE {record.grade}</span></div><div className="text-xs"><b className="text-emerald-600">● Kararlı</b><p className="text-[10px] text-gray-400 mt-2">Kayıt etkileşimleri ve planlanan adımlardan hesaplanır.</p></div></div></Card><Card title="Kontrol notları">{record.readinessNotes.length ? record.readinessNotes.map(note=><p key={note} className="rounded-xl bg-[#ecfdf5] border border-emerald-200 px-3 py-2 text-xs mb-2">✓ {note}</p>) : <p className="text-xs text-gray-400">Kontrol notu bulunmuyor.</p>}</Card></div></div>
  </section>;
}
function Stat({label,value}:{label:string;value:string}){return <div className="flex flex-col gap-0.5"><span className="text-gray-400 font-bold uppercase text-[9px] tracking-wider">{label}</span><span className="text-gray-900 font-bold max-w-28 truncate">{value || "—"}</span></div>}
function Card({title,children}:{title:string;children:ReactNode}){return <div className="bg-white border border-gray-200/60 rounded-3xl p-5 shadow-xs"><h3 className="text-sm font-bold text-gray-900 border-b border-gray-100 pb-2 mb-4">{title}</h3>{children}</div>}
function Row({label,value}:{label:string;value:string}){return <div className="grid grid-cols-3 gap-3 py-2 border-b border-gray-100 last:border-0 text-xs"><span className="text-gray-400 font-semibold">{label}</span><span className="col-span-2 font-medium break-all">{value || "—"}</span></div>}
